<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Admin user létrehozása
        DB::table('users')->insert([
            'name' => 'Admin',
            'email' => 'admin@rapidmotors.com',
            'password' => Hash::make('Admin123!'),
            'is_admin' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Oldtimer autók (5 db)
        $oldtimers = [
            [
                'name' => 'Chevelle SS',
                'manufacturer' => 'Chevrolet',
                'year' => 1970,
                'category' => 'oldtimer',
                'price' => 45000000.00,
                'horsepower' => 450,
                'engine' => '7.4L V8 LS6',
                'top_speed' => 210.0,
                'acceleration' => 5.4,
                'description' => 'Az amerikai "muscle car" éra egyik legmeghatározóbb darabja. Brutális erő és összetéveszthetetlen forma.',
                'is_featured' => false,
            ],
            [
                'name' => '300SL Gullwing',
                'manufacturer' => 'Mercedes-Benz',
                'year' => 1955,
                'category' => 'oldtimer',
                'price' => 432000000.00,
                'horsepower' => 215,
                'engine' => '3.0L I6',
                'top_speed' => 260.0,
                'acceleration' => 8.8,
                'description' => 'Ikonikus sirályszárnyú ajtókkal rendelkező sportkocsi. Az 50-es évek szuperautója.',
                'is_featured' => true,
            ],
            [
                'name' => 'E-Type Series 1',
                'manufacturer' => 'Jaguar',
                'year' => 1961,
                'category' => 'oldtimer',
                'price' => 102000000.00,
                'horsepower' => 265,
                'engine' => '3.8L I6',
                'top_speed' => 241.0,
                'acceleration' => 7.1,
                'description' => 'Enzo Ferrari szerint a legszebb autó amit valaha készítettek. Brit elegancia és teljesítmény.',
                'is_featured' => false,
            ],
            [
                'name' => '250 GTO',
                'manufacturer' => 'Ferrari',
                'year' => 1962,
                'category' => 'oldtimer',
                'price' => 17280000000.00,
                'horsepower' => 300,
                'engine' => '3.0L V12',
                'top_speed' => 280.0,
                'acceleration' => 6.1,
                'description' => 'A világ legértékesebb autója. Mindössze 36 darab készült belőle.',
                'is_featured' => true,
            ],
            [
                'name' => '911 Carrera RS 2.7',
                'manufacturer' => 'Porsche',
                'year' => 1973,
                'category' => 'oldtimer',
                'price' => 342000000.00,
                'horsepower' => 210,
                'engine' => '2.7L Flat-6',
                'top_speed' => 245.0,
                'acceleration' => 5.8,
                'description' => 'A legenda kezdete. Az első RS kacsafarokkal és ikonikus dizájnnal.',
                'is_featured' => false,
            ],
        ];

        // Szuperautók (15 db)
        $supercars = [
            [
                'name' => 'Chiron',
                'manufacturer' => 'Bugatti',
                'year' => 2021,
                'category' => 'supercar',
                'price' => 1080000000.00,
                'horsepower' => 1500,
                'engine' => '8.0L W16 Quad-Turbo',
                'top_speed' => 420.0,
                'acceleration' => 2.4,
                'description' => 'A Bugatti hiperautó megtestesítője. 1500 lóerő, négyturbós W16 motor és elektronikusan korlátozott 420 km/h-s végsebesség.',
                'is_featured' => true,
            ],
            [
                'name' => 'SF90 Stradale',
                'manufacturer' => 'Ferrari',
                'year' => 2023,
                'category' => 'supercar',
                'price' => 225000000.00,
                'horsepower' => 1000,
                'engine' => '4.0L V8 + 3 E-Motor',
                'top_speed' => 340.0,
                'acceleration' => 2.5,
                'description' => 'Ferrari első plug-in hybrid szuperautója. 1000 lóerő kombinált teljesítménnyel.',
                'is_featured' => true,
            ],
            [
                'name' => 'Aventador SVJ',
                'manufacturer' => 'Lamborghini',
                'year' => 2023,
                'category' => 'supercar',
                'price' => 206000000.00,
                'horsepower' => 770,
                'engine' => '6.5L V12',
                'top_speed' => 350.0,
                'acceleration' => 2.8,
                'description' => 'A természetesen szívott V12 búcsúszimfóniája. Nürburgring rekorder.',
                'is_featured' => true,
            ],
            [
                'name' => '720S',
                'manufacturer' => 'McLaren',
                'year' => 2024,
                'category' => 'supercar',
                'price' => 113400000.00,
                'horsepower' => 720,
                'engine' => '4.0L V8 Twin-Turbo',
                'top_speed' => 341.0,
                'acceleration' => 2.9,
                'description' => 'McLaren szupersorozatának gyöngyszeme. Káprázatos teljesítmény és dizájn.',
                'is_featured' => false,
            ],
            [
                'name' => '918 Spyder',
                'manufacturer' => 'Porsche',
                'year' => 2023,
                'category' => 'supercar',
                'price' => 648000000.00,
                'horsepower' => 887,
                'engine' => '4.6L V8 + 2 E-Motor',
                'top_speed' => 345.0,
                'acceleration' => 2.6,
                'description' => 'A szent hármasság német tagja. Elektromos és benzines erő tökéletes szimbiózisa.',
                'is_featured' => true,
            ],
            [
                'name' => 'AMG One',
                'manufacturer' => 'Mercedes-AMG',
                'year' => 2024,
                'category' => 'supercar',
                'price' => 972000000.00,
                'horsepower' => 1063,
                'engine' => '1.6L V6 Turbo Hybrid',
                'top_speed' => 352.0,
                'acceleration' => 2.9,
                'description' => 'F1 motor az utcán. Lewis Hamilton technológiája civilian változatban.',
                'is_featured' => true,
            ],
            [
                'name' => 'Huayra BC',
                'manufacturer' => 'Pagani',
                'year' => 2023,
                'category' => 'supercar',
                'price' => 1224000000.00,
                'horsepower' => 800,
                'engine' => '6.0L V12 Twin-Turbo',
                'top_speed' => 370.0,
                'acceleration' => 2.8,
                'description' => 'Művészet négy keréken. Benny Caiola tiszteletére készült limitált szériás csoda.',
                'is_featured' => false,
            ],
            [
                'name' => 'Gemera',
                'manufacturer' => 'Koenigsegg',
                'year' => 2024,
                'category' => 'supercar',
                'price' => 612000000.00,
                'horsepower' => 1700,
                'engine' => '2.0L I3 + 3 E-Motor',
                'top_speed' => 400.0,
                'acceleration' => 1.9,
                'description' => 'A világ első négyüléses megahyperautója. Családi szuperautó új definíciója.',
                'is_featured' => true,
            ],
            [
                'name' => 'Valkyrie',
                'manufacturer' => 'Aston Martin',
                'year' => 2023,
                'category' => 'supercar',
                'price' => 1152000000.00,
                'horsepower' => 1160,
                'engine' => '6.5L V12 Hybrid',
                'top_speed' => 402.0,
                'acceleration' => 2.5,
                'description' => 'Adrian Newey F1 mérnök remeke. Szélcsatorna és utca közötti határ.',
                'is_featured' => true,
            ],
            [
                'name' => 'GT2 RS',
                'manufacturer' => 'Porsche',
                'year' => 2024,
                'category' => 'supercar',
                'price' => 125000000.00,
                'horsepower' => 700,
                'engine' => '3.8L Flat-6 Twin-Turbo',
                'top_speed' => 340.0,
                'acceleration' => 2.7,
                'description' => 'A leggyorsabb utcai legális 911. Nürburgring pályarekord-tartó.',
                'is_featured' => false,
            ],
            [
                'name' => 'Senna',
                'manufacturer' => 'McLaren',
                'year' => 2023,
                'category' => 'supercar',
                'price' => 396000000.00,
                'horsepower' => 800,
                'engine' => '4.0L V8 Twin-Turbo',
                'top_speed' => 340.0,
                'acceleration' => 2.8,
                'description' => 'Ayrton Senna emlékére. Tiszta pályaautó karakter utcai rendszámmal.',
                'is_featured' => false,
            ],
            [
                'name' => 'Revuelto',
                'manufacturer' => 'Lamborghini',
                'year' => 2024,
                'category' => 'supercar',
                'price' => 218800000.00,
                'horsepower' => 1015,
                'engine' => '6.5L V12 + 3 E-Motor',
                'top_speed' => 350.0,
                'acceleration' => 2.5,
                'description' => 'Lamborghini első V12 plug-in hybridja. Az Aventador utódja.',
                'is_featured' => true,
            ],
            [
                'name' => 'Jesko Absolut',
                'manufacturer' => 'Koenigsegg',
                'year' => 2024,
                'category' => 'supercar',
                'price' => 1080000000.00,
                'horsepower' => 1600,
                'engine' => '5.0L V8 Twin-Turbo',
                'top_speed' => 531.0,
                'acceleration' => 2.5,
                'description' => 'Koenigsegg végsebességre optimalizált hyperautója. Elméleti maximum: 531 km/h.',
                'is_featured' => true,
            ],
            [
                'name' => 'LaFerrari',
                'manufacturer' => 'Ferrari',
                'year' => 2023,
                'category' => 'supercar',
                'price' => 1152000000.00,
                'horsepower' => 963,
                'engine' => '6.3L V12 Hybrid',
                'top_speed' => 350.0,
                'acceleration' => 2.4,
                'description' => 'A szent hármasság olasz tagja. Ferrari első hibrid hyperautója.',
                'is_featured' => true,
            ],
            [
                'name' => 'Venom F5',
                'manufacturer' => 'Hennessey',
                'year' => 2024,
                'category' => 'supercar',
                'price' => 756000000.00,
                'horsepower' => 1817,
                'engine' => '6.6L V8 Twin-Turbo',
                'top_speed' => 484.0,
                'acceleration' => 2.6,
                'description' => 'Amerikai hypercar. Cél: 500 km/h megdöntése.',
                'is_featured' => false,
            ],
        ];

        // Luxusautók (5 db)
        $luxuryCars = [
            [
                'name' => 'DBX707',
                'manufacturer' => 'Aston Martin',
                'year' => 2024,
                'category' => 'luxury',
                'price' => 84600000.00,
                'horsepower' => 707,
                'engine' => '4.0L V8 Twin-Turbo',
                'top_speed' => 310.0,
                'acceleration' => 3.3,
                'description' => 'A világ legerősebb luxus SUV-ja. Brit elegancia és brutális teljesítmény.',
                'is_featured' => false,
            ],
            [
                'name' => 'Speedtail',
                'manufacturer' => 'McLaren',
                'year' => 2023,
                'category' => 'luxury',
                'price' => 810000000.00,
                'horsepower' => 1070,
                'engine' => '4.0L V8 Hybrid',
                'top_speed' => 403.0,
                'acceleration' => 2.9,
                'description' => 'A McLaren F1 szellemi utódja. Központi vezetőülés, három ülés.',
                'is_featured' => true,
            ],
            [
                'name' => 'Battista',
                'manufacturer' => 'Pininfarina',
                'year' => 2024,
                'category' => 'luxury',
                'price' => 792000000.00,
                'horsepower' => 1900,
                'engine' => 'Quad Electric Motor',
                'top_speed' => 350.0,
                'acceleration' => 1.9,
                'description' => 'Tisztán elektromos hyperscar olasz dizájnnal. 1900 lóerő csendben.',
                'is_featured' => true,
            ],
            [
                'name' => 'Urus Performante',
                'manufacturer' => 'Lamborghini',
                'year' => 2024,
                'category' => 'luxury',
                'price' => 93600000.00,
                'horsepower' => 666,
                'engine' => '4.0L V8 Twin-Turbo',
                'top_speed' => 306.0,
                'acceleration' => 3.3,
                'description' => 'Szuper SUV Lamborghini módra. Pályaautó képességek családi csomagtartóval.',
                'is_featured' => false,
            ],
            [
                'name' => 'SLS AMG GT',
                'manufacturer' => 'Mercedes-Benz',
                'year' => 2013,
                'category' => 'luxury',
                'price' => 75000000.00,
                'horsepower' => 583,
                'engine' => '6.2L V8',
                'top_speed' => 320.0,
                'acceleration' => 3.7,
                'description' => 'Ikonikus sirályszárnyas szuperautó brutális V8 hanggal és klasszikus AMG karakterrel.',
                'is_featured' => false,
            ],
        ];

        // Autók beszúrása (5 oldtimer + 15 szuperautó + 5 luxusautó = 25 db)
        foreach (array_merge($oldtimers, $supercars, $luxuryCars) as $car) {
            DB::table('cars')->insert(array_merge($car, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
